  on:
    pull_request:
      types: [opened, synchronize]
  
  jobs:
    explain_code:
      runs-on: ubuntu-latest
      name: ChatGPT Explain Code
      steps:
        - name: ChatGPT Explain Code
          uses: richmiles/chatgpt-github-actions@v0.9.8-beta
          with:
            openai_api_key: ${{ secrets.OPENAI_API_KEY }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
            github_pr_id: ${{ github.event.number }}
            openai_engine: "gpt-3.5-turbo" #optional
            openai_temperature: 0.5 #optional
            openai_max_tokens: 2048 #optional
            mode: files # files or patch
            included_file_extensions: "js"
            include_tokens_in_output: true